# Generated by Django 3.2.8 on 2021-12-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pd_triple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prescriberid', models.IntegerField()),
                ('drugname', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
