# Generated by Django 3.2.8 on 2021-12-03 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdCredential',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pd_credential',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdDrugs',
            fields=[
                ('drugid', models.IntegerField(primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdPrescriber',
            fields=[
                ('npi', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('credentials', models.CharField(blank=True, max_length=30, null=True)),
                ('isopioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pd_prescriber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdSpecialty',
            fields=[
                ('title', models.CharField(max_length=62, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pd_specialty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdStatedata',
            fields=[
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_statedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriberCredential',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prescriber_id', models.IntegerField()),
                ('credential_title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prescriber_credential',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriberSpecialty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prescriber_specialty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdTriplenew',
            fields=[
                ('prescriberid', models.OneToOneField(db_column='prescriberid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WebApp.pdprescriber')),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_triplenew',
                'managed': False,
            },
        ),
    ]
