# Generated by Django 3.2.8 on 2021-12-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdcredential',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pddrugs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pdspecialty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pdstatedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pdtriplenew',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescribercredential',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriberspecialty',
            options={},
        ),
    ]
