# Generated by Django 3.2.8 on 2021-12-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20211204_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdprescriber',
            old_name='state',
            new_name='stateid',
        ),
    ]
