# Generated by Django 3.2.8 on 2021-12-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_pdprescriber_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdprescriber',
            name='drugs',
            field=models.ManyToManyField(to='WebApp.PdDrugs'),
        ),
    ]
