# Generated by Django 3.2.8 on 2021-12-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_pdprescriber_drugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdPrescriberDrugs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('pddrugs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.pddrugs')),
                ('pdprescriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.pdprescriber')),
            ],
            options={
                'db_table': 'pd_prescriber_drugs',
                'unique_together': {('pdprescriber', 'pddrugs')},
            },
        ),
        migrations.AlterField(
            model_name='pdprescriber',
            name='drugs',
            field=models.ManyToManyField(through='WebApp.PdPrescriberDrugs', to='WebApp.PdDrugs'),
        ),
    ]
