# Generated by Django 3.2.8 on 2021-12-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20211204_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdprescriberdrugs',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
