# Generated by Django 3.2.8 on 2021-12-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_pdprescriberdrugs_qty2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdprescriber',
            old_name='stateid',
            new_name='state',
        ),
    ]
