# Generated by Django 3.2.8 on 2021-12-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_rename_stateid_pdprescriber_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdprescriber',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.pdstatedata'),
        ),
    ]
