# Generated by Django 3.2.8 on 2021-12-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_pdprescriber_hi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdPrescriberSpecialtiesLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdprescriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.pdprescriber')),
                ('pdspecialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.pdspecialty')),
            ],
            options={
                'db_table': 'pd_prescriber_specialties_link',
                'unique_together': {('pdprescriber', 'pdspecialty')},
            },
        ),
        migrations.AlterField(
            model_name='pdprescriber',
            name='specialties',
            field=models.ManyToManyField(through='WebApp.PdPrescriberSpecialtiesLink', to='WebApp.PdSpecialty'),
        ),
    ]
